





CREATE DATABASE IF NOT EXISTS kangnamtime
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE kangnamtime;


CREATE USER IF NOT EXISTS 'kangnamtime'@'localhost' IDENTIFIED BY '4321';


GRANT ALL PRIVILEGES ON kangnamtime.* TO 'kangnamtime'@'localhost';
FLUSH PRIVILEGES;


SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS BOARD_LIKE;
DROP TABLE IF EXISTS BOARD_SCRAP;
DROP TABLE IF EXISTS BOARD_COMMENT;
DROP TABLE IF EXISTS BOARD_POST;
DROP TABLE IF EXISTS ASSIGNMENT;
DROP TABLE IF EXISTS LECTURE;
DROP TABLE IF EXISTS USER_INTEGRATION;
DROP TABLE IF EXISTS MEMBER;

SET FOREIGN_KEY_CHECKS = 1;




CREATE TABLE MEMBER (
    MEMBER_NO   INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID     VARCHAR(50)  NOT NULL UNIQUE,
    USER_PW     VARCHAR(200) NOT NULL,        
    NAME        VARCHAR(50)  NOT NULL,
    MAJOR       VARCHAR(100),
    CREATED_AT  DATETIME     DEFAULT NOW()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;





CREATE TABLE USER_INTEGRATION (
    USER_ID       VARCHAR(50)  NOT NULL,
    EVERYTIME_ID  VARCHAR(100),
    EVERYTIME_PW  VARCHAR(200),
    KANGNAM_ID  VARCHAR(100),
    KANGNAM_PW  VARCHAR(200),
    ECAMPUS_ID    VARCHAR(100),
    ECAMPUS_PW    VARCHAR(200),
    UPDATED_AT    DATETIME     DEFAULT NOW(),
    CONSTRAINT PK_USER_INTEGRATION PRIMARY KEY (USER_ID),
    CONSTRAINT FK_UI_MEMBER FOREIGN KEY (USER_ID)
        REFERENCES MEMBER(USER_ID)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;




CREATE TABLE BOARD_POST (
    POST_NO        INT AUTO_INCREMENT PRIMARY KEY,   
    USER_ID        VARCHAR(50) NOT NULL,             
    TITLE          VARCHAR(200) NOT NULL,
    CONTENT        TEXT NOT NULL,                    
    HIT            INT DEFAULT 0,                    
    LIKE_COUNT     INT DEFAULT 0,                    
    SCRAP_COUNT    INT DEFAULT 0,                    
    COMMENT_COUNT  INT DEFAULT 0,                    
    CREATED_AT     DATETIME DEFAULT NOW(),

    CONSTRAINT FK_POST_MEMBER
        FOREIGN KEY (USER_ID)
        REFERENCES MEMBER(USER_ID)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;






CREATE TABLE BOARD_COMMENT (
    COMMENT_NO   INT AUTO_INCREMENT PRIMARY KEY,
    POST_NO      INT          NOT NULL,
    USER_ID      VARCHAR(50)  NOT NULL,
    CONTENT      TEXT         NOT NULL,
    CREATED_AT   DATETIME     DEFAULT NOW(),
    UPDATED_AT   DATETIME,
    IS_DELETED   CHAR(1)      NOT NULL DEFAULT 'N',
    CONSTRAINT FK_BC_POST FOREIGN KEY (POST_NO)
        REFERENCES BOARD_POST(POST_NO)
        ON DELETE CASCADE,
    CONSTRAINT FK_BC_MEMBER FOREIGN KEY (USER_ID)
        REFERENCES MEMBER(USER_ID)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;





CREATE TABLE BOARD_LIKE (
    POST_NO      INT         NOT NULL,
    USER_ID      VARCHAR(50) NOT NULL,
    CREATED_AT   DATETIME    DEFAULT NOW(),
    CONSTRAINT PK_BOARD_LIKE PRIMARY KEY (POST_NO, USER_ID),
    CONSTRAINT FK_BL_POST FOREIGN KEY (POST_NO)
        REFERENCES BOARD_POST(POST_NO)
        ON DELETE CASCADE,
    CONSTRAINT FK_BL_MEMBER FOREIGN KEY (USER_ID)
        REFERENCES MEMBER(USER_ID)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;




CREATE TABLE BOARD_SCRAP (
    POST_NO      INT         NOT NULL,
    USER_ID      VARCHAR(50) NOT NULL,
    CREATED_AT   DATETIME    DEFAULT NOW(),
    CONSTRAINT PK_BOARD_SCRAP PRIMARY KEY (POST_NO, USER_ID),
    CONSTRAINT FK_BS_POST FOREIGN KEY (POST_NO)
        REFERENCES BOARD_POST(POST_NO)
        ON DELETE CASCADE,
    CONSTRAINT FK_BS_MEMBER FOREIGN KEY (USER_ID)
        REFERENCES MEMBER(USER_ID)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;




CREATE TABLE ASSIGNMENT (
    ASSIGN_NO      INT AUTO_INCREMENT PRIMARY KEY,   
    USER_ID        VARCHAR(50)  NOT NULL,            
    TITLE          VARCHAR(200) NOT NULL,            
    COURSE_NAME    VARCHAR(200),                     
    DESCRIPTION    TEXT,                             
    START_DATE     DATE,                             
    DUE_DATE       DATE        NOT NULL,             
    PRIORITY       INT,                              
    STATUS         VARCHAR(20),                      
    CREATED_AT     DATETIME DEFAULT NOW(),           
    UPDATED_AT     DATETIME,                         
    IS_PASSED      TINYINT(1),                       
    LINK           VARCHAR(1000),                    

    CONSTRAINT FK_ASSIGN_MEMBER
        FOREIGN KEY (USER_ID)
        REFERENCES MEMBER(USER_ID)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;





CREATE TABLE LECTURE (
    LECTURE_ID   INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID      VARCHAR(50)  NOT NULL,
    TITLE        VARCHAR(200) NOT NULL,       
    DAY          VARCHAR(10),                 
    START_MIN    INT,                         
    END_MIN      INT,                         
    LOCATION     VARCHAR(200),                
    COLOR        VARCHAR(20),                 
    CREATED_AT   DATETIME     DEFAULT NOW(),
    UPDATED_AT   DATETIME,
    CONSTRAINT FK_LEC_MEMBER FOREIGN KEY (USER_ID)
        REFERENCES MEMBER(USER_ID)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE market_item (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,      
    title VARCHAR(100) NOT NULL,              
    category VARCHAR(30) NOT NULL,            
    price INT NOT NULL,                       
    status VARCHAR(20) NOT NULL,              
    campus VARCHAR(30) NOT NULL,              
    meeting_place VARCHAR(100) NULL,          
    meeting_time VARCHAR(100) NULL,           
    trade_type VARCHAR(20) NOT NULL,          
    wish_count INT NOT NULL DEFAULT 0,        
    chat_count INT NOT NULL DEFAULT 0,        
    thumbnail_url VARCHAR(255) NULL,          
    description TEXT NULL,                    
    writer_id INT NULL,                       
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE BOARD_NOTICE (
    NOTICE_NO   INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID     VARCHAR(50)  NOT NULL,
    TITLE       VARCHAR(200) NOT NULL,
    CONTENT     MEDIUMTEXT   NOT NULL,
    HIT         INT          NOT NULL DEFAULT 0,
    CREATED_AT  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_general_ci;

CREATE TABLE USER_TIMETABLE (
    TT_NO       INT AUTO_INCREMENT PRIMARY KEY,   
    USER_ID     VARCHAR(50)      NOT NULL,        
    TITLE       VARCHAR(200)     NOT NULL,        
    PROFESSOR   VARCHAR(100),                     
    DAY         TINYINT          NOT NULL,        
    START_MIN   INT              NOT NULL,        
    END_MIN     INT              NOT NULL,        
    UPDATED_AT  DATETIME         NOT NULL DEFAULT CURRENT_TIMESTAMP  
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE market_buyer_address (
  buyer_id INT PRIMARY KEY,
  recipient_name VARCHAR(50) NOT NULL,
  phone VARCHAR(20) NOT NULL,
  postcode VARCHAR(10) NOT NULL,
  address1 VARCHAR(255) NOT NULL,
  address2 VARCHAR(255),
  memo VARCHAR(255),
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);




CREATE TABLE IF NOT EXISTS market_cart (
    cart_id    BIGINT AUTO_INCREMENT PRIMARY KEY,
    member_no  INT NOT NULL,
    item_id    BIGINT NOT NULL,
    cart_type  ENUM('IMMEDIATE','DELIVERY') NOT NULL,
    quantity   INT NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    UNIQUE KEY uq_member_item_type (member_no, item_id, cart_type),
    KEY idx_member (member_no),

    CONSTRAINT fk_cart_member FOREIGN KEY (member_no) REFERENCES MEMBER(MEMBER_NO) ON DELETE CASCADE,
    CONSTRAINT fk_cart_item   FOREIGN KEY (item_id) REFERENCES market_item(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;




CREATE TABLE IF NOT EXISTS market_chat_room (
    room_id     BIGINT AUTO_INCREMENT PRIMARY KEY,
    item_id     BIGINT NOT NULL,
    seller_id   INT NOT NULL,
    buyer_id    INT NOT NULL,
    created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    UNIQUE KEY uq_item_buyer (item_id, buyer_id),
    KEY idx_seller (seller_id),
    KEY idx_buyer (buyer_id),
    CONSTRAINT fk_chat_room_item FOREIGN KEY (item_id) REFERENCES market_item(id) ON DELETE CASCADE,
    CONSTRAINT fk_chat_room_seller FOREIGN KEY (seller_id) REFERENCES MEMBER(MEMBER_NO) ON DELETE CASCADE,
    CONSTRAINT fk_chat_room_buyer FOREIGN KEY (buyer_id) REFERENCES MEMBER(MEMBER_NO) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS market_chat_message (
    msg_id     BIGINT AUTO_INCREMENT PRIMARY KEY,
    room_id    BIGINT NOT NULL,
    sender_id  INT NOT NULL,
    message    TEXT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    KEY idx_room_msg (room_id, msg_id),
    CONSTRAINT fk_chat_msg_room FOREIGN KEY (room_id) REFERENCES market_chat_room(room_id) ON DELETE CASCADE,
    CONSTRAINT fk_chat_msg_sender FOREIGN KEY (sender_id) REFERENCES MEMBER(MEMBER_NO) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE market_order (
  order_id BIGINT AUTO_INCREMENT PRIMARY KEY,
  item_id BIGINT NOT NULL,
  seller_id INT NOT NULL,
  buyer_id INT NOT NULL,
  price INT NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'PAID',
  carrier VARCHAR(50),
  tracking_number VARCHAR(100),
  paid_at DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  shipped_at DATETIME,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE market_order
  ADD COLUMN recipient_name VARCHAR(50) NOT NULL,
  ADD COLUMN phone VARCHAR(20) NOT NULL,
  ADD COLUMN postcode VARCHAR(10) NOT NULL,
  ADD COLUMN address1 VARCHAR(255) NOT NULL,
  ADD COLUMN address2 VARCHAR(255) NULL,
  ADD COLUMN memo VARCHAR(255) NULL;

CREATE TABLE IF NOT EXISTS market_wish (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  item_id BIGINT NOT NULL,
  member_no INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_item_member (item_id, member_no),
  INDEX idx_member (member_no)
);


ALTER TABLE market_item 
ADD COLUMN instant_buy TINYINT(1) NOT NULL DEFAULT 0,
ADD COLUMN buyer_id INT NULL,
ADD COLUMN sold_at DATETIME NULL;

ALTER TABLE market_cart 
ADD UNIQUE KEY uk_cart (member_no, item_id, cart_type);

ALTER TABLE market_chat_message
ADD COLUMN message_type VARCHAR(20) NOT NULL DEFAULT 'USER',
MODIFY COLUMN sender_id INT NULL;

ALTER TABLE market_chat_room
ADD COLUMN seller_last_read_msg_id BIGINT NOT NULL DEFAULT 0,
ADD COLUMN buyer_last_read_msg_id BIGINT NOT NULL DEFAULT 0;

