CREATE TABLE market_order (
  order_id BIGINT AUTO_INCREMENT PRIMARY KEY,
  item_id BIGINT NOT NULL,
  seller_id INT NOT NULL,
  buyer_id INT NOT NULL,
  price INT NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'PAID',
  carrier VARCHAR(50),
  tracking_number VARCHAR(100),
  paid_at DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  shipped_at DATETIME,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE market_order
  ADD COLUMN recipient_name VARCHAR(50) NOT NULL,
  ADD COLUMN phone VARCHAR(20) NOT NULL,
  ADD COLUMN postcode VARCHAR(10) NOT NULL,
  ADD COLUMN address1 VARCHAR(255) NOT NULL,
  ADD COLUMN address2 VARCHAR(255) NULL,
  ADD COLUMN memo VARCHAR(255) NULL;

